const products = [
    {
        title: "Apple Airpods MRXJ2HN/A with Wireless Charging Case (White)",
        image: "/images/airpods.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 16999,
        brand: "Apple",
        category: "Electronics",
        stock: 10,
        rating: 4.5,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "Amazon Echo Plus 2nd Gen Alexa Built-in Smart Speaker (B0794JD9JS, Black)",
        image: "/images/alexa.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 11990,
        brand: "Amazon",
        category: "Electronics",
        stock: 4,
        rating: 1.5,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "GoPro Hero 9 20MP Action Camera (1080p Live Stream, Black)",
        image: "/images/gopro.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 36999,
        brand: "GoPro",
        category: "Electronics",
        stock: 4,
        rating: 4.5,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "Apple iMac (MGPC3HN/A) M1 Chip macOS Big Sur (8GB RAM, 256GB SSD, Apple 8 Core GPU, 60.96cm (24 Inches), Silver)",
        image: "/images/imac.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 132990,
        brand: "Apple",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "Apple iPad Pro 11 3rd Gen WiFi iOS Tablet (iPadOS 14, Apple M1 Chip, 27.96 cm (11 Inches), 16GB RAM, 1TB ROM, MHQY3HN/A, Space Grey)",
        image: "/images/ipad.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 134990,
        brand: "Apple",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "Oculus Quest 2 — Advanced All-In-One Virtual Reality Headset — 128 GB",
        image: "/images/oculus.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 29999,
        brand: "Oculus",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "Apple Pencil 2nd Generation (MU8F2ZM/A, White)",
        image: "/images/pencil.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 10990,
        brand: "Apple",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "SONY PLAYSTATION®5",
        image: "/images/ps5.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 10990,
        brand: "Sony",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "V-Raptor",
        image: "/images/redcamera.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 620385,
        brand: "Red",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },
    {
        title: "Thrustmaster T248",
        image: "/images/steering.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed at illo unde, ea impedit necessitatibus velit voluptas iste obcaecati. Explicabo saepe repellat architecto quam nostrum ullam earum. Error, officia aliquid.",
        price: 620385,
        brand: "Thrustmaster",
        category: "Electronics",
        stock: 4,
        rating: 4,
        number_reviews: 5,
        count_in_stock: 10,
        reviews : []
    },

];
// exports.products = products;
// module.exports = products;
export default products